'use client';

import { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Download, Printer, Share2 } from 'lucide-react';
import { Card, Badge } from '@/components/ui/primitives';
import { Button } from '@/components/ui/button';
import { cn, getInitials, instrumentLabel, formatDate, formatTime } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';
import { useMember, useMemberAttendanceSummary } from '@/lib/hooks/use-members';
import { useMemberAttendanceHistory } from '@/lib/hooks/use-attendance';

const tabs = ['My Card', 'Attendance', 'Notifications'] as const;

export default function MemberPortalPage() {
  const [activeTab, setActiveTab] = useState<typeof tabs[number]>('My Card');
  const userId = useAuthStore((s) => s.userId);

  // In production this would resolve via /members/me using the authenticated userId
  const { data: member } = useMember(userId ?? undefined);
  const { data: summary } = useMemberAttendanceSummary(member?.id);
  const { data: history } = useMemberAttendanceHistory(member?.id);

  if (!member) {
    return <p className="py-10 text-center text-sm text-ink-secondary">Loading profile…</p>;
  }

  return (
    <div>
      <div className="mb-5 flex items-center gap-4 border-b border-border pb-5">
        <div className="flex h-13 w-13 items-center justify-center rounded-full bg-primary-accent text-base font-medium text-primary">
          {getInitials(member.full_name)}
        </div>
        <div>
          <p className="text-lg font-semibold text-ink">{member.full_name}</p>
          <p className="text-sm text-ink-secondary">
            <span className="font-mono">{member.member_id}</span> ·{' '}
            {instrumentLabel[member.instrument]} · Active since{' '}
            {member.joining_date && formatDate(member.joining_date)}
          </p>
        </div>
      </div>

      <div className="mb-5 flex gap-1 rounded-md bg-background p-1">
        {tabs.map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={cn(
              'flex-1 rounded-md px-3 py-2 text-sm transition-colors',
              activeTab === tab
                ? 'bg-surface font-medium text-ink shadow-sm'
                : 'text-ink-secondary hover:text-ink',
            )}
          >
            {tab}
          </button>
        ))}
      </div>

      {activeTab === 'My Card' && (
        <div className="space-y-5">
          <div className="relative overflow-hidden rounded-xl bg-gradient-to-br from-primary to-primary-light p-6 text-white">
            <p className="text-[11px] uppercase tracking-wide text-white/70">
              Avishkar Dhol Tasha Pathak
            </p>
            <div className="mt-3 flex h-12 w-12 items-center justify-center rounded-full bg-white/20 text-sm font-medium">
              {getInitials(member.full_name)}
            </div>
            <p className="mt-3 text-lg font-semibold">{member.full_name}</p>
            <p className="font-mono text-xs text-white/70">{member.member_id}</p>
            <div className="mt-3 space-y-0.5 text-sm text-white/90">
              <p>🥁 {instrumentLabel[member.instrument]}</p>
              <p>📱 {member.mobile_number}</p>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2">
            <Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" /> PDF</Button>
            <Button variant="outline" size="sm"><Printer className="h-3.5 w-3.5" /> Print</Button>
            <Button variant="outline" size="sm"><Share2 className="h-3.5 w-3.5" /> Share</Button>
          </div>

          <Card className="flex flex-col items-center gap-3 p-6">
            <p className="text-sm font-medium text-ink">My QR Code</p>
            <QRCodeSVG
              value={JSON.stringify({ memberId: member.member_id })}
              size={180}
              fgColor="#3C3489"
            />
            <p className="text-center text-xs text-ink-secondary">
              Secure encrypted token · regenerated by admin if needed
            </p>
          </Card>
        </div>
      )}

      {activeTab === 'Attendance' && summary && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <Card className="p-4">
              <p className="text-xl font-semibold text-success">{summary.present_count}</p>
              <p className="text-xs text-ink-secondary">Present</p>
            </Card>
            <Card className="p-4">
              <p className="text-xl font-semibold text-danger">{summary.absent_count}</p>
              <p className="text-xs text-ink-secondary">Absent</p>
            </Card>
            <Card className="p-4">
              <p className="text-xl font-semibold text-primary">
                {summary.attendance_percentage}%
              </p>
              <p className="text-xs text-ink-secondary">Attendance Rate</p>
            </Card>
            <Card className="p-4">
              <p className="text-xl font-semibold text-warning">{summary.late_count}</p>
              <p className="text-xs text-ink-secondary">Late Arrivals</p>
            </Card>
          </div>

          <Card>
            <div className="border-b border-border p-4">
              <p className="text-sm font-medium text-ink">Recent Attendance</p>
            </div>
            <div className="divide-y divide-border">
              {history?.map((record) => (
                <div key={record.id} className="flex items-center justify-between p-3.5">
                  <span className="text-sm text-ink">
                    {record.check_in_time ? formatDate(record.check_in_time) : '—'}
                  </span>
                  <span className="text-xs text-ink-secondary">
                    {record.check_in_time ? formatTime(record.check_in_time) : ''}
                  </span>
                  <Badge
                    variant={
                      record.attendance_status === 'present' ? 'success'
                      : record.attendance_status === 'late' ? 'warning' : 'danger'
                    }
                  >
                    {record.attendance_status}
                  </Badge>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}

      {activeTab === 'Notifications' && (
        <Card className="p-8 text-center text-sm text-ink-secondary">
          Notifications will appear here as they arrive.
        </Card>
      )}
    </div>
  );
}
